### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [ChaitanyaPramod/findbugs-android#14]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by ChaitanyaPramod** [comment]
Sure @jbeguna04, would love one.

There's currently this simple logo - 
![Current logo](https://github.com/ChaitanyaPramod/findbugs-android/raw/47769e8107c5bd64dc4b25fd119d76e7c9541ba1/docs/images/logo.png)

**Comment by jbeguna04** [comment]
Thank you for your response. Ill be presenting the designs here afterwards. Best regards

**Comment by jbeguna04** [comment]
Greetings @ChaitanyaPramod , These is my proposal for your project. Feel free to have suggestions
![fingbugs-01](https://user-images.githubusercontent.com/35353768/41038857-38b347ae-69ca-11e8-8c1c-73dd9b68dff1.png)
Best Regards,
-jbeguna04

**Comment by ChaitanyaPramod** [comment]
Hi @jbeguna04, thanks for your proposals, they look good.

However, we can't use them presently. This project is an integration project and I'd like to represent elements of the related projects (Android, Findbugs) like in the existing logo shared above. Would love to see if you've any ideas like that.

**Comment by jbeguna04** [comment]
Thank you for your response, I will be proposing more related to Android and bugs designs asap.

**Comment by jbeguna04** [comment]
![rfrer](https://user-images.githubusercontent.com/35353768/42353762-2be5fd86-80f5-11e8-971f-e5577f25d09a.png)
Here is my second proposal for your project. Please give suggestions or any changes you want.
Best regards,
jbeguna04

**Comment by ChaitanyaPramod** [comment]
Can you create a PR with the logos, please?

**Comment by jbeguna04** [comment]
Yes sure sir. @ChaitanyaPramod. Did you like it?

**Comment by ChaitanyaPramod** [comment]
Closed by PR #17
