### ISSUE TITLE
Question regarding design

### ISSUE THREAD

**Issue by yashasvigirdhar** [ChaitanyaPramod/findbugs-android#20]
Hi,

Thank you for this library.

I was curious why are we adding findbug tasks as subtasks of `check` task.

Any particular reason for doing that?

**Comment by ChaitanyaPramod** [comment]
You're welcome 😊

This is a convention that comes from the [Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html#lifecycle_tasks) which itself inherits it from [Base plugin](https://docs.gradle.org/current/userguide/base_plugin.html#sec:base_tasks)

`check` is a lifecycle task which by itself doesn't do anything and is used by other plugins (like Java plugin) to hook verification and sanity checking tasks onto it. As Findbugs flags potential issues in code (like Android lint), its tasks are hooked on the `check` task.

**Comment by yashasvigirdhar** [comment]
That makes sense. Thanks!
